version: "3.8"
services:
  db:
    image: mysql:8.0.30
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "backend_database"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    container_name: mysql_db_container
  backend:
    build:
      context: .
    restart: always
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    image: backend:django
    container_name: django_backend_container
    entrypoint: /docker/run.sh
    depends_on:
      - db
