version: "3.8"
services:
  backend:
    build: .
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    image: backend:django
    container_name: django_backend_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "backend_database"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    container_name: mysql_db_container
