version: "3.8"
services:
  db:
    image: mysql:8.0.30
    volumes:
      - /var/lib/${DATABASE_VOLUME}/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    container_name: mysql_db_container
  backend:
    build:
      context: .
    volumes:
      - .:/backend
      - ./google_vision_api_credentials.json:/google_vision_api_credentials.json
    ports:
      - 8000:8000
    image: python1002/django:backend
    container_name: django_backend_container
    entrypoint: /docker/run.sh
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ${NGINX_CONFIG_PATH}:${NGINX_SERVER_CONFIG_PATH}
      - ./flutter/build/app:/var/www/html/po3backend.ddns.net/app
      - ./flutter/build/web:/var/www/html/po3backend.ddns.net/web
    ports:
      - 80:80
      - 443:443
    container_name: nginx_server
    depends_on:
      - backend
    networks:
      - docker-network
  #certbot:
  #image: certbot/certbot
  #container_name: certbot
  #volumes:
  #  - ./certbot/conf:/etc/letsencrypt
  #  - ./certbot/www:/var/www/certbot
  #command: certonly --webroot -w /var/www/certbot --email robin.martens1@student.kuleuven.be -d po3backend.ddns.net --agree-tos --non-interactive
networks:
  docker-network:
    driver: bridge
