version: "3.8"
services:
  db:
    image: mysql:8.0.30
    volumes:
      - /var/lib/po3_backend_data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "backend_database"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    container_name: mysql_db_container
  backend:
    build:
      context: .
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    image: backend:django
    container_name: django_backend_container
    entrypoint: /docker/run.sh
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    container_name: nginx_server
    depends_on:
      - backend
