# Generated by Django 4.1.2 on 2022-11-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.garage'),
        ),
    ]
