# Generated by Django 4.1.2 on 2022-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fav_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
    ]
