# Generated by Django 4.1.2 on 2022-12-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_strikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
    ]
