# Generated by Django 4.1.2 on 2022-11-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_owner_garage_user'),
        ('users', '0002_user_fav_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_garage', to='api.garage'),
        ),
    ]
