# Generated by Django 4.1.2 on 2022-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_two_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_validated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
