# Generated by Django 4.1.2 on 2022-11-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Generated User'), (1, 'Normal User'), (2, 'Garage Owner'), (3, 'Admin')]),
        ),
    ]
