# Generated by Django 4.1.2 on 2022-12-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_two_factor_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_identifier',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
