# Generated by Django 4.1.2 on 2022-11-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parkinglots_disabled_settings_prices_openinghours_and_more'),
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.settings'),
            preserve_default=False,
        ),
    ]
