# Generated by Django 4.1.2 on 2022-11-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_fav_garage_id_settings_fav_garage_and_more"),
        ("users", "0005_user_settings_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="settings_id",
        ),
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="api.settings",
            ),
            preserve_default=False,
        ),
    ]
