# Generated by Django 4.1.2 on 2022-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_fav_garage_id_settings_fav_garage_and_more'),
        ('users', '0006_remove_user_settings_id_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.settings'),
        ),
    ]
