# Generated by Django 4.1.2 on 2022-11-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
    ]
