# Generated by Django 4.1.2 on 2022-11-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_locations_garage_remove_settings_user'),
        ('users', '0008_remove_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.settings'),
        ),
    ]
