# Generated by Django 4.1.2 on 2022-11-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_reservations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fav_garage",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.garages"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                choices=[
                    (None, "(Unknown)"),
                    ("ANT", "Antwerpen"),
                    ("HAI", "Henegouwen"),
                    ("LIE", "Luik"),
                    ("LIM", "Limburg"),
                    ("LUX", "Luxemburg"),
                    ("NAM", "Namen"),
                    ("OVL", "Oost-Vlaanderen"),
                    ("WVL", "West-Vlaanderen"),
                    ("VBR", "Vlaams-Brabant"),
                    ("WBR", "Waals-Brabant"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
