# Generated by Django 4.1.2 on 2022-11-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_fav_garage_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
    ]
