# Generated by Django 4.1.2 on 2022-11-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20221116_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[(None, 'UNK'), ('ANT', 'Antwerpen'), ('HAI', 'Henegouwen'), ('LIE', 'Luik'), ('LIM', 'Limburg'), ('LUX', 'Luxemburg'), ('NAM', 'Namen'), ('OVL', 'Oost-Vlaanderen'), ('WVL', 'West-Vlaanderen'), ('VBR', 'Vlaams-Brabant'), ('WBR', 'Waals-Brabant')], max_length=3, null=True),
        ),
    ]
