# Generated by Django 4.1.2 on 2022-11-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=192)),
            ],
            options={
                'db_table': 'garages',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=192)),
                ('province', models.CharField(choices=[(None, 'UNK'), ('ANT', 'Antwerpen'), ('HAI', 'Henegouwen'), ('LIE', 'Luik'), ('LIM', 'Limburg'), ('LUX', 'Luxemburg'), ('NAM', 'Namen'), ('OVL', 'Oost-Vlaanderen'), ('WVL', 'West-Vlaanderen'), ('VBR', 'Vlaams-Brabant'), ('WBR', 'Waals-Brabant')], max_length=3)),
                ('municipality', models.CharField(max_length=192)),
                ('post_code', models.IntegerField()),
                ('street', models.CharField(max_length=192)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_number', models.IntegerField()),
                ('occupied', models.BooleanField()),
                ('disabled', models.BooleanField(default=False)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
            ],
            options={
                'db_table': 'parking_lots',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_string', models.CharField(max_length=192)),
                ('price', models.FloatField()),
                ('valuta', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('GBP', 'Pound')], default='EUR', max_length=3)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('to_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
            ],
            options={
                'db_table': 'opening_hours',
            },
        ),
        migrations.CreateModel(
            name='LicencePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('licence_plate', models.CharField(max_length=192, unique=True)),
                ('garage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licence_plates',
            },
        ),
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_height', models.FloatField()),
                ('max_width', models.FloatField()),
                ('max_handicapped_lots', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
            options={
                'db_table': 'garage_settings',
            },
        ),
        migrations.AddField(
            model_name='garage',
            name='garage_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagesettings'),
        ),
        migrations.AddField(
            model_name='garage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
