# Generated by Django 4.1.2 on 2022-12-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage'),
        ),
        migrations.AddField(
            model_name='openinghour',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garage'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenceplate',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.garage'),
        ),
        migrations.AddField(
            model_name='licenceplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garagesettings',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='garage',
            name='garage_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagesettings'),
        ),
        migrations.AddField(
            model_name='garage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='parkinglot',
            unique_together={('parking_lot_no', 'garage')},
        ),
    ]
