# Generated by Django 4.1.2 on 2022-11-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='owner',
            new_name='user',
        ),
    ]
