# Generated by Django 4.1.2 on 2022-12-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='unoccupied_lots',
            field=models.IntegerField(default=0),
        ),
    ]
