# Generated by Django 4.1.2 on 2022-10-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_licenceplates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenceplates',
            name='entered_at',
        ),
        migrations.AddField(
            model_name='licenceplates',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.garages'),
        ),
        migrations.AlterField(
            model_name='licenceplates',
            name='licence_plate',
            field=models.CharField(max_length=192, unique=True),
        ),
    ]
