# Generated by Django 4.1.2 on 2022-12-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_garage_unoccupied_lots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='unoccupied_lots',
            new_name='entered',
        ),
    ]
