# Generated by Django 4.1.2 on 2022-11-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parkinglot_parking_lot_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkinglot',
            unique_together={('parking_lot_no', 'garage')},
        ),
    ]
