# Generated by Django 4.1.2 on 2022-12-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_parkinglot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesettings',
            name='electric_cars',
            field=models.IntegerField(default=0),
        ),
    ]
