# Generated by Django 4.1.2 on 2022-11-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_location_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='garage',
        ),
    ]
