# Generated by Django 4.1.2 on 2022-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_licenceplate_entered_at_licenceplate_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='showed',
            field=models.BooleanField(default=False),
        ),
    ]
