# Generated by Django 4.1.2 on 2022-11-15 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_rename_garage_id_garagesettings_garage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='fav_garage_id',
            new_name='fav_garage',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='user_id',
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
