# Generated by Django 4.1.2 on 2022-11-29 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_parkinglot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='price',
            name='stripe_identifier',
            field=models.CharField(default='price_1M5XwcGRh96C3wQGkqJqXCmi', max_length=30),
        ),
    ]
