# Generated by Django 4.1.2 on 2022-11-29 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_price_duration_price_stripe_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
