# Generated by Django 4.1.2 on 2022-12-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reservation_showed'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='reservations',
            field=models.IntegerField(default=0),
        ),
    ]
