# Generated by Django 4.1.2 on 2022-11-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_fav_garage_id_settings_fav_garage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
    ]
