# Generated by Django 4.1.2 on 2022-11-15 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_locations_garage_remove_settings_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openinghours",
            old_name="day_from",
            new_name="from_day",
        ),
        migrations.RenameField(
            model_name="openinghours",
            old_name="day_to",
            new_name="to_day",
        ),
        migrations.RemoveField(
            model_name="garagesettings",
            name="garage",
        ),
        migrations.RemoveField(
            model_name="openinghours",
            name="hour_from",
        ),
        migrations.RemoveField(
            model_name="openinghours",
            name="hour_to",
        ),
        migrations.AddField(
            model_name="garages",
            name="garage_settings",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.garagesettings",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openinghours",
            name="from_hour",
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openinghours",
            name="to_hour",
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
