# Generated by Django 4.1.2 on 2022-12-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_garage_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='reservations',
        ),
    ]
