# Generated by Django 4.1.2 on 2022-11-29 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_price_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
