# Generated by Django 4.1.2 on 2022-12-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_garage_reservations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='licence_plate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.licenceplate'),
            preserve_default=False,
        ),
    ]
