# Generated by Django 4.1.2 on 2022-12-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_garagesettings_electric_cars'),
        ('api', '0008_alter_price_duration'),
    ]

    operations = [
    ]
