# Generated by Django 4.1.2 on 2022-12-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20221208_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='licence_plate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.licenceplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking_lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot'),
        ),
    ]
