# Generated by Django 4.1.2 on 2022-12-20 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_parkinglot_licence_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='licence_plate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.licenceplate'),
        ),
    ]
