# Generated by Django 4.1.2 on 2022-12-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_reservation_user_reservation_licence_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parkinglot'),
        ),
    ]
