# Generated by Django 4.1.2 on 2022-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_locations_province_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='province',
            field=models.CharField(choices=[(None, '(Unknown)'), ('ANT', 'Antwerpen'), ('HAI', 'Henegouwen'), ('LIE', 'Luik'), ('LIM', 'Limburg'), ('LUX', 'Luxemburg'), ('NAM', 'Namen'), ('OVL', 'Oost-Vlaanderen'), ('WVL', 'West-Vlaanderen'), ('VBR', 'Vlaams-Brabant'), ('WBR', 'Waals-Brabant')], max_length=3),
        ),
    ]
