# Generated by Django 4.1.2 on 2022-12-20 23:38

from django.db import migrations, models
import src.api.models.garage.price


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_parkinglot_licence_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(validators=[src.api.models.garage.price.validate_greater_than_zero]),
        ),
    ]
