# Generated by Django 4.1.2 on 2022-11-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_locations_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='garage',
        ),
    ]
