# Generated by Django 4.1.2 on 2022-12-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_card'),
        ('api', '0012_reservation_user'),
    ]

    operations = [
    ]
