# Generated by Django 4.1.2 on 2022-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenceplate',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
