# Generated by Django 4.1.2 on 2022-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_licenceplate_enabled'),
        ('api', '0013_merge_0009_card_0012_reservation_user'),
    ]

    operations = [
    ]
