# Generated by Django 4.1.2 on 2022-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20221213_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
