name: Backend Build
on:
  push:
    branch: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN 3
        run: |
          sudo apt install apt-transport-https
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-jammy.list
          sudo apt update
          sudo apt install openvpn3
      - name: Create config.ovpn and certificate
        run: |
          mkdir .github/vpn && touch .github/vpn/config.ovpn
          echo -e "remote ${{ secrets.VPN_URL }}\ncomp-lzo\nobind\ndev tun\nproto udp\nport ${{ secrets.VPN_PORT }}\nauth-nocache\npersist-key\npersist-tun\nclient\nca dnetcloudssh.crt" > .github/vpn/config.ovpn
          echo "${{ secrets.VPN_CA_CRT }}" > .github/vpn/dnetcloudssh.crt
      - name: Create password file
        run: |
          echo "${{ secrets.VPN_USERNAME }}" > .github/vpn/dnetcloud.pw
          echo "${{ secrets.VPN_PASSWORD }}" >> .github/vpn/dnetcloud.pw
      - name: Connect VPN
        run: openvpn3 --config .github/vpn/config.ovpn --ca .github/vpn/dnetcloudssh.crt  
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami

      - name: kill vpn
        if: always()
        run: sudo killall openvpn
