name: Backend Build
on:
  push:
    branch: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Create config.ovpn
        run: |
        touch .github/vpn/config.ovpn
        echo -e "remote ${{ secrets.VPN_URL }}\ncomp-lzo\nobind\ndev tun\nproto udp\nport ${{ secrets.VPN_PORT }}\nauth-nocache\npersist-key\npersist-tun\nclient\nca ca.crt" > .github/vpn/config.ovpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: ${{ secrets.VPN_URL }}
          FILE_OVPN: ".github/vpn/config.ovpn"
          SECRET: ${{ secrets.VPN_CREDENTIALS }}
        env:
          CA_CRT: ${{ secrets.VPN_CA_CRT}}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami

      - name: kill vpn
        if: always()
        run: sudo killall openvpn
