name: Backend Build
on:
  push:
    branch: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn
      - name: Create config.ovpn and certificate
        run: |
          mkdir .github/vpn && touch .github/vpn/config.ovpn
          echo -e "remote $VPN_URL\ncomp-lzo\nobind\ndev tun\nproto udp\nport $VPN_PORT\nauth-nocache\npersist-key\npersist-tun\nclient\nca dnetcloudssh.crt" > .github/vpn/config.ovpn
          cat .github/vpn/config.ovpn
          echo "$VPN_CA_CRT" > .github/vpn/dnetcloudssh.crt
        env:
          VPN_CA: ${{ secrets.VPN_CA_CRT }}
          VPN_PORT: ${{ secrets.VPN_PORT }}
          VPN_URL: ${{ secrets.VPN_URL }}
      - name: Create password file
        run: |
          echo "${{ secrets.VPN_USERNAME }}" > .github/vpn/dnetcloud.pw
          echo "${{ secrets.VPN_PASSWORD }}" >> .github/vpn/dnetcloud.pw
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      - name: Connect VPN
        run: openvpn --config .github/vpn/config.ovpn --ca .github/vpn/dnetcloudssh.crt --auth-user-pass .github/vpn/dnetcloud.pw
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami

      - name: kill vpn
        if: always()
        run: sudo killall openvpn
